ALTER TABLE "User"
ALTER COLUMN "middle_name" DROP NOT NULL,
ALTER COLUMN "middle_name" DROP DEFAULT,
ALTER COLUMN "display_name" DROP NOT NULL,
ALTER COLUMN "display_name" DROP DEFAULT,
ALTER COLUMN "primary_handle" DROP NOT NULL,
ALTER COLUMN "primary_handle" DROP DEFAULT,
ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "phone_number" DROP DEFAULT,
ALTER COLUMN "timezone" DROP NOT NULL,
ALTER COLUMN "timezone" DROP DEFAULT;
