ALTER TABLE "User"
ADD COLUMN "middle_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "display_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "primary_handle" TEXT NOT NULL DEFAULT '',
ADD COLUMN "bio" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone_number" TEXT NOT NULL DEFAULT '',
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Asia/Manila';
